name: Testing on MacOS
on:
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        # NPM 7 is compatible with Node.js 15 or above
        node-version: [15.x, 16.x]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v2

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts --audit=false --fund=false

      - run: echo "Building... 🛠"
      - run: npm run build

      - run: echo "Testing... 😵‍💫"
      - run: npm run test

      - run: echo "🍏 This job's status is ${{ job.status }}."
